apiVersion: v1
kind: Service
metadata:
  name: lance-cv
  namespace: lance-cv
  labels:
    app.kubernetes.io/name: lance-cv
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lance-cv
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http